#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v5
# autospec commit: c02b2fe
#
Name     : gtkwave
Version  : 3.3.119
Release  : 24
URL      : https://gtkwave.sourceforge.net/gtkwave-3.3.119.tar.gz
Source0  : https://gtkwave.sourceforge.net/gtkwave-3.3.119.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MIT bzip2-1.0.6
Requires: gtkwave-bin = %{version}-%{release}
Requires: gtkwave-data = %{version}-%{release}
Requires: gtkwave-license = %{version}-%{release}
Requires: gtkwave-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : desktop-file-utils
BuildRequires : flex
BuildRequires : gperf
BuildRequires : pkgconfig(gconf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-unix-print-2.0)
BuildRequires : pkgconfig(libtirpc)
BuildRequires : tcl
BuildRequires : tcl-dev
BuildRequires : tk
BuildRequires : tk-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
1) Type ./configure
2) make
3) make install (as root)
Make sure you copy the .gtkwaverc file to your home directory or to your
VCD project directory.  It contains the prefs for a good configuration
that most people find ergonomic.  It is not strictly necessary however.

%package bin
Summary: bin components for the gtkwave package.
Group: Binaries
Requires: gtkwave-data = %{version}-%{release}
Requires: gtkwave-license = %{version}-%{release}

%description bin
bin components for the gtkwave package.


%package data
Summary: data components for the gtkwave package.
Group: Data

%description data
data components for the gtkwave package.


%package license
Summary: license components for the gtkwave package.
Group: Default

%description license
license components for the gtkwave package.


%package man
Summary: man components for the gtkwave package.
Group: Default

%description man
man components for the gtkwave package.


%prep
%setup -q -n gtkwave-3.3.119
cd %{_builddir}/gtkwave-3.3.119
pushd ..
cp -a gtkwave-3.3.119 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711743578
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --disable-schemas-compile --disable-mime-update \
--disable-xz
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --disable-schemas-compile --disable-mime-update \
--disable-xz
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1711743578
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gtkwave
cp %{_builddir}/gtkwave-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gtkwave/13d2034b5ee3cb8d1a076370cf8f0e344a5d0855 || :
cp %{_builddir}/gtkwave-%{version}/LICENSE.TXT %{buildroot}/usr/share/package-licenses/gtkwave/93a24b78a50ec984bc2b7b13a8041ddded409712 || :
cp %{_builddir}/gtkwave-%{version}/src/libbz2/LICENSE %{buildroot}/usr/share/package-licenses/gtkwave/1c0c6888759a63c32bca7eb63353af2cd9bd5d9e || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/evcd2vcd
/V3/usr/bin/fst2vcd
/V3/usr/bin/fstminer
/V3/usr/bin/gtkwave
/V3/usr/bin/lxt2miner
/V3/usr/bin/lxt2vcd
/V3/usr/bin/rtlbrowse
/V3/usr/bin/shmidcat
/V3/usr/bin/twinwave
/V3/usr/bin/vcd2fst
/V3/usr/bin/vcd2lxt
/V3/usr/bin/vcd2lxt2
/V3/usr/bin/vcd2vzt
/V3/usr/bin/vzt2vcd
/V3/usr/bin/vztminer
/V3/usr/bin/xml2stems
/usr/bin/evcd2vcd
/usr/bin/fst2vcd
/usr/bin/fstminer
/usr/bin/gtkwave
/usr/bin/lxt2miner
/usr/bin/lxt2vcd
/usr/bin/rtlbrowse
/usr/bin/shmidcat
/usr/bin/twinwave
/usr/bin/vcd2fst
/usr/bin/vcd2lxt
/usr/bin/vcd2lxt2
/usr/bin/vcd2vzt
/usr/bin/vzt2vcd
/usr/bin/vztminer
/usr/bin/xml2stems

%files data
%defattr(-,root,root,-)
/usr/share/applications/gtkwave.desktop
/usr/share/gtkwave/examples/des.fst
/usr/share/gtkwave/examples/des.gtkw
/usr/share/gtkwave/examples/des.tcl
/usr/share/gtkwave/examples/des.v
/usr/share/gtkwave/examples/gtkwaverc
/usr/share/gtkwave/examples/sst_exclusion_example.rc
/usr/share/gtkwave/examples/transaction.c
/usr/share/gtkwave/examples/transaction.fst
/usr/share/gtkwave/examples/transaction.gtkw
/usr/share/gtkwave/gtkwave.odt
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-ae2.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-aet.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-evcd.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-fst.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-ghw.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-gtkw.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-lx2.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-lxt.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-lxt2.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-vcd.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-vzt.png
/usr/share/icons/gnome/16x16/mimetypes/gtkwave.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-ae2.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-aet.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-evcd.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-fst.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-ghw.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-gtkw.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-lx2.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-lxt.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-lxt2.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-vcd.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-vzt.png
/usr/share/icons/gnome/32x32/mimetypes/gtkwave.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-ae2.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-aet.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-evcd.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-fst.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-ghw.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-gtkw.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-lx2.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-lxt.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-lxt2.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-vcd.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-vzt.png
/usr/share/icons/gnome/48x48/mimetypes/gtkwave.png
/usr/share/icons/gtkwave_256x256x32.png
/usr/share/icons/gtkwave_files_256x256x32.png
/usr/share/icons/gtkwave_savefiles_256x256x32.png
/usr/share/icons/hicolor/scalable/apps/gtkwave.svg
/usr/share/mime-packages/x-gtkwave-extension-ae2.xml
/usr/share/mime-packages/x-gtkwave-extension-aet.xml
/usr/share/mime-packages/x-gtkwave-extension-evcd.xml
/usr/share/mime-packages/x-gtkwave-extension-fst.xml
/usr/share/mime-packages/x-gtkwave-extension-ghw.xml
/usr/share/mime-packages/x-gtkwave-extension-gtkw.xml
/usr/share/mime-packages/x-gtkwave-extension-lx2.xml
/usr/share/mime-packages/x-gtkwave-extension-lxt.xml
/usr/share/mime-packages/x-gtkwave-extension-lxt2.xml
/usr/share/mime-packages/x-gtkwave-extension-vcd.xml
/usr/share/mime-packages/x-gtkwave-extension-vzt.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gtkwave/13d2034b5ee3cb8d1a076370cf8f0e344a5d0855
/usr/share/package-licenses/gtkwave/1c0c6888759a63c32bca7eb63353af2cd9bd5d9e
/usr/share/package-licenses/gtkwave/93a24b78a50ec984bc2b7b13a8041ddded409712

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/evcd2vcd.1
/usr/share/man/man1/fst2vcd.1
/usr/share/man/man1/fstminer.1
/usr/share/man/man1/gtkwave.1
/usr/share/man/man1/lxt2miner.1
/usr/share/man/man1/lxt2vcd.1
/usr/share/man/man1/rtlbrowse.1
/usr/share/man/man1/shmidcat.1
/usr/share/man/man1/twinwave.1
/usr/share/man/man1/vcd2fst.1
/usr/share/man/man1/vcd2lxt.1
/usr/share/man/man1/vcd2lxt2.1
/usr/share/man/man1/vcd2vzt.1
/usr/share/man/man1/vzt2vcd.1
/usr/share/man/man1/vztminer.1
/usr/share/man/man1/xml2stems.1
/usr/share/man/man5/gtkwaverc.5
