#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gtkwave
Version  : 3.3.100
Release  : 1
URL      : http://gtkwave.sourceforge.net/gtkwave-3.3.100.tar.gz
Source0  : http://gtkwave.sourceforge.net/gtkwave-3.3.100.tar.gz
Summary  : A wave viewer which reads LXT, LXT2, VZT, GHW and VCD/EVCD files
Group    : Development/Tools
License  : GPL-2.0 MIT TCL bzip2-1.0.6
Requires: gtkwave-bin = %{version}-%{release}
Requires: gtkwave-data = %{version}-%{release}
Requires: gtkwave-license = %{version}-%{release}
Requires: gtkwave-man = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : desktop-file-utils
BuildRequires : flex
BuildRequires : gperf
BuildRequires : pkgconfig(gconf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-unix-print-2.0)
BuildRequires : pkgconfig(libtirpc)
BuildRequires : tcl
BuildRequires : tcl-dev
BuildRequires : tk
BuildRequires : tk-dev
BuildRequires : xz-dev

%description
ZLIB DATA COMPRESSION LIBRARY
zlib 1.2.11 is a general purpose data compression library.  All the code is
thread safe.  The data format used by the zlib library is described by RFCs
(Request for Comments) 1950 to 1952 in the files
http://tools.ietf.org/html/rfc1950 (zlib format), rfc1951 (deflate format) and
rfc1952 (gzip format).

%package bin
Summary: bin components for the gtkwave package.
Group: Binaries
Requires: gtkwave-data = %{version}-%{release}
Requires: gtkwave-license = %{version}-%{release}

%description bin
bin components for the gtkwave package.


%package data
Summary: data components for the gtkwave package.
Group: Data

%description data
data components for the gtkwave package.


%package license
Summary: license components for the gtkwave package.
Group: Default

%description license
license components for the gtkwave package.


%package man
Summary: man components for the gtkwave package.
Group: Default

%description man
man components for the gtkwave package.


%prep
%setup -q -n gtkwave-3.3.100

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554733523
%configure --disable-static --disable-schemas-compile --disable-mime-update
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1554733523
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gtkwave
cp COPYING %{buildroot}/usr/share/package-licenses/gtkwave/COPYING
cp LICENSE.TXT %{buildroot}/usr/share/package-licenses/gtkwave/LICENSE.TXT
cp src/libbz2/LICENSE %{buildroot}/usr/share/package-licenses/gtkwave/src_libbz2_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/evcd2vcd
/usr/bin/fst2vcd
/usr/bin/fstminer
/usr/bin/ghwdump
/usr/bin/gtkwave
/usr/bin/lxt2miner
/usr/bin/lxt2vcd
/usr/bin/rtlbrowse
/usr/bin/shmidcat
/usr/bin/twinwave
/usr/bin/vcd2fst
/usr/bin/vcd2lxt
/usr/bin/vcd2lxt2
/usr/bin/vcd2vzt
/usr/bin/vzt2vcd
/usr/bin/vztminer
/usr/bin/xml2stems

%files data
%defattr(-,root,root,-)
/usr/share/applications/gtkwave.desktop
/usr/share/gtkwave/examples/des.fst
/usr/share/gtkwave/examples/des.gtkw
/usr/share/gtkwave/examples/des.tcl
/usr/share/gtkwave/examples/des.v
/usr/share/gtkwave/examples/gtkwaverc
/usr/share/gtkwave/examples/sst_exclusion_example.rc
/usr/share/gtkwave/examples/transaction.c
/usr/share/gtkwave/examples/transaction.fst
/usr/share/gtkwave/examples/transaction.gtkw
/usr/share/gtkwave/gtkwave.odt
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-ae2.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-aet.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-evcd.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-fst.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-ghw.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-gtkw.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-lx2.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-lxt.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-lxt2.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-vcd.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-vzt.png
/usr/share/icons/gnome/16x16/mimetypes/gtkwave.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-ae2.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-aet.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-evcd.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-fst.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-ghw.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-gtkw.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-lx2.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-lxt.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-lxt2.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-vcd.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-vzt.png
/usr/share/icons/gnome/32x32/mimetypes/gtkwave.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-ae2.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-aet.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-evcd.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-fst.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-ghw.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-gtkw.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-lx2.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-lxt.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-lxt2.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-vcd.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-vzt.png
/usr/share/icons/gnome/48x48/mimetypes/gtkwave.png
/usr/share/icons/gtkwave_256x256x32.png
/usr/share/icons/gtkwave_files_256x256x32.png
/usr/share/icons/gtkwave_savefiles_256x256x32.png
/usr/share/icons/hicolor/scalable/apps/gtkwave.svg
/usr/share/mime-packages/x-gtkwave-extension-ae2.xml
/usr/share/mime-packages/x-gtkwave-extension-aet.xml
/usr/share/mime-packages/x-gtkwave-extension-evcd.xml
/usr/share/mime-packages/x-gtkwave-extension-fst.xml
/usr/share/mime-packages/x-gtkwave-extension-ghw.xml
/usr/share/mime-packages/x-gtkwave-extension-gtkw.xml
/usr/share/mime-packages/x-gtkwave-extension-lx2.xml
/usr/share/mime-packages/x-gtkwave-extension-lxt.xml
/usr/share/mime-packages/x-gtkwave-extension-lxt2.xml
/usr/share/mime-packages/x-gtkwave-extension-vcd.xml
/usr/share/mime-packages/x-gtkwave-extension-vzt.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gtkwave/COPYING
/usr/share/package-licenses/gtkwave/LICENSE.TXT
/usr/share/package-licenses/gtkwave/src_libbz2_LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/evcd2vcd.1
/usr/share/man/man1/fst2vcd.1
/usr/share/man/man1/fstminer.1
/usr/share/man/man1/ghwdump.1
/usr/share/man/man1/gtkwave.1
/usr/share/man/man1/lxt2miner.1
/usr/share/man/man1/lxt2vcd.1
/usr/share/man/man1/rtlbrowse.1
/usr/share/man/man1/shmidcat.1
/usr/share/man/man1/twinwave.1
/usr/share/man/man1/vcd2fst.1
/usr/share/man/man1/vcd2lxt.1
/usr/share/man/man1/vcd2lxt2.1
/usr/share/man/man1/vcd2vzt.1
/usr/share/man/man1/vzt2vcd.1
/usr/share/man/man1/vztminer.1
/usr/share/man/man1/xml2stems.1
/usr/share/man/man5/gtkwaverc.5
