#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gtkwave
Version  : 3.3.110
Release  : 14
URL      : http://gtkwave.sourceforge.net/gtkwave-3.3.110.tar.gz
Source0  : http://gtkwave.sourceforge.net/gtkwave-3.3.110.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MIT bzip2-1.0.6
Requires: gtkwave-bin = %{version}-%{release}
Requires: gtkwave-data = %{version}-%{release}
Requires: gtkwave-license = %{version}-%{release}
Requires: gtkwave-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : desktop-file-utils
BuildRequires : flex
BuildRequires : gperf
BuildRequires : pkgconfig(gconf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-unix-print-2.0)
BuildRequires : pkgconfig(libtirpc)
BuildRequires : tcl
BuildRequires : tcl-dev
BuildRequires : tk
BuildRequires : tk-dev
BuildRequires : xz-dev

%description
1) Type ./configure
2) make
3) make install (as root)
Make sure you copy the .gtkwaverc file to your home directory or to your
VCD project directory.  It contains the prefs for a good configuration
that most people find ergonomic.  It is not strictly necessary however.

%package bin
Summary: bin components for the gtkwave package.
Group: Binaries
Requires: gtkwave-data = %{version}-%{release}
Requires: gtkwave-license = %{version}-%{release}

%description bin
bin components for the gtkwave package.


%package data
Summary: data components for the gtkwave package.
Group: Data

%description data
data components for the gtkwave package.


%package license
Summary: license components for the gtkwave package.
Group: Default

%description license
license components for the gtkwave package.


%package man
Summary: man components for the gtkwave package.
Group: Default

%description man
man components for the gtkwave package.


%prep
%setup -q -n gtkwave-3.3.110
cd %{_builddir}/gtkwave-3.3.110

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1624289520
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --disable-schemas-compile --disable-mime-update
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1624289520
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gtkwave
cp %{_builddir}/gtkwave-3.3.110/COPYING %{buildroot}/usr/share/package-licenses/gtkwave/13d2034b5ee3cb8d1a076370cf8f0e344a5d0855
cp %{_builddir}/gtkwave-3.3.110/LICENSE.TXT %{buildroot}/usr/share/package-licenses/gtkwave/813da07dd825e76cae603ccc4b59f1e5f4b1dc40
cp %{_builddir}/gtkwave-3.3.110/src/libbz2/LICENSE %{buildroot}/usr/share/package-licenses/gtkwave/1c0c6888759a63c32bca7eb63353af2cd9bd5d9e
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/evcd2vcd
/usr/bin/fst2vcd
/usr/bin/fstminer
/usr/bin/gtkwave
/usr/bin/lxt2miner
/usr/bin/lxt2vcd
/usr/bin/rtlbrowse
/usr/bin/shmidcat
/usr/bin/twinwave
/usr/bin/vcd2fst
/usr/bin/vcd2lxt
/usr/bin/vcd2lxt2
/usr/bin/vcd2vzt
/usr/bin/vzt2vcd
/usr/bin/vztminer
/usr/bin/xml2stems

%files data
%defattr(-,root,root,-)
/usr/share/applications/gtkwave.desktop
/usr/share/gtkwave/examples/des.fst
/usr/share/gtkwave/examples/des.gtkw
/usr/share/gtkwave/examples/des.tcl
/usr/share/gtkwave/examples/des.v
/usr/share/gtkwave/examples/gtkwaverc
/usr/share/gtkwave/examples/sst_exclusion_example.rc
/usr/share/gtkwave/examples/transaction.c
/usr/share/gtkwave/examples/transaction.fst
/usr/share/gtkwave/examples/transaction.gtkw
/usr/share/gtkwave/gtkwave.odt
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-ae2.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-aet.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-evcd.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-fst.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-ghw.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-gtkw.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-lx2.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-lxt.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-lxt2.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-vcd.png
/usr/share/icons/gnome/16x16/mimetypes/gnome-mime-application-vnd.gtkwave-vzt.png
/usr/share/icons/gnome/16x16/mimetypes/gtkwave.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-ae2.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-aet.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-evcd.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-fst.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-ghw.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-gtkw.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-lx2.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-lxt.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-lxt2.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-vcd.png
/usr/share/icons/gnome/32x32/mimetypes/gnome-mime-application-vnd.gtkwave-vzt.png
/usr/share/icons/gnome/32x32/mimetypes/gtkwave.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-ae2.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-aet.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-evcd.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-fst.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-ghw.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-gtkw.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-lx2.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-lxt.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-lxt2.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-vcd.png
/usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.gtkwave-vzt.png
/usr/share/icons/gnome/48x48/mimetypes/gtkwave.png
/usr/share/icons/gtkwave_256x256x32.png
/usr/share/icons/gtkwave_files_256x256x32.png
/usr/share/icons/gtkwave_savefiles_256x256x32.png
/usr/share/icons/hicolor/scalable/apps/gtkwave.svg
/usr/share/mime-packages/x-gtkwave-extension-ae2.xml
/usr/share/mime-packages/x-gtkwave-extension-aet.xml
/usr/share/mime-packages/x-gtkwave-extension-evcd.xml
/usr/share/mime-packages/x-gtkwave-extension-fst.xml
/usr/share/mime-packages/x-gtkwave-extension-ghw.xml
/usr/share/mime-packages/x-gtkwave-extension-gtkw.xml
/usr/share/mime-packages/x-gtkwave-extension-lx2.xml
/usr/share/mime-packages/x-gtkwave-extension-lxt.xml
/usr/share/mime-packages/x-gtkwave-extension-lxt2.xml
/usr/share/mime-packages/x-gtkwave-extension-vcd.xml
/usr/share/mime-packages/x-gtkwave-extension-vzt.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gtkwave/13d2034b5ee3cb8d1a076370cf8f0e344a5d0855
/usr/share/package-licenses/gtkwave/1c0c6888759a63c32bca7eb63353af2cd9bd5d9e
/usr/share/package-licenses/gtkwave/813da07dd825e76cae603ccc4b59f1e5f4b1dc40

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/evcd2vcd.1
/usr/share/man/man1/fst2vcd.1
/usr/share/man/man1/fstminer.1
/usr/share/man/man1/gtkwave.1
/usr/share/man/man1/lxt2miner.1
/usr/share/man/man1/lxt2vcd.1
/usr/share/man/man1/rtlbrowse.1
/usr/share/man/man1/shmidcat.1
/usr/share/man/man1/twinwave.1
/usr/share/man/man1/vcd2fst.1
/usr/share/man/man1/vcd2lxt.1
/usr/share/man/man1/vcd2lxt2.1
/usr/share/man/man1/vcd2vzt.1
/usr/share/man/man1/vzt2vcd.1
/usr/share/man/man1/vztminer.1
/usr/share/man/man1/xml2stems.1
/usr/share/man/man5/gtkwaverc.5
